### ISSUE TITLE
Question about Instrument tree in CNES

### ISSUE THREAD

**Issue by BaptisteCecconi** [hpde/CNES#2]
Most (or all) instruments in this repository are already defined elsewhere. I guess I understand why this has been done in the first place, but I fear this could lead to inconsistencies in the future: 
- this requires to monitor source records and update CDPP-AMDA ones (`spase://SMWG/Instrument/Cassini/RPWS` and `spase://CNES/Instrument/CDPP-AMDA/Cassini/RPWS` have different content as of now).
- this also duplicates and splits references to instruments, so that traceability may be broken.
- this will make advanced search engines more complex to build (how to discover CDPP-AMDA records using `spase://SMWG/Instrument/Cassini/RPWS`? => not possible at this point)

**Comment by brenard-irap** [comment]
Hi Baptiste,
We are agree with your comment and this will be done in the second place.

**Comment by BaptisteCecconi** [comment]
good :-)
