### ISSUE TITLE
Unknown Interball metadata in CNES repository

### ISSUE THREAD

**Issue by dpopcdpp** [hpde/CNES#3]
Under CNES/NumericalData we find interball, metadata not comming from CNES archive in the folder https://github.com/hpde/CNES/tree/master/NumericalData/Interball-1)/ELECTRON/ 
We propose to suppress these data, because the up to date and complete metadata (including Interball) will be delivered with the rest of the CDPP missions.

**Comment by tressahelvey** [comment]
Danielle, we just noticed this issue. Has anyone worked on it? Can we close the ticket?? Thank you.

**Comment by tressahelvey** [comment]
Per Daniele, this issue can be closed.
![image](https://github.com/hpde/CNES/assets/108490588/f389dc7f-45f6-430b-b32e-92d09a71b827)
