### ISSUE TITLE
ResourceName values are not descriptive enough

### ISSUE THREAD

**Issue by berniegsfc** [hpde/CNES#5]
The `/Spase/NumericalData/ResourceHeader/ResourceName` value in most, if not all, `CNES` documents are not descriptive enough.  One example is [spase://CNES/NumericalData/CDPP-AMDA/MAVEN/MAG/mav-mag-pds](https://hpde.io/CNES/NumericalData/CDPP-AMDA/MAVEN/MAG/mav-mag-pds.html).  See attached screenshot of how they are displayed in the Heliophysics Data Portal.
<img width="778" alt="Screenshot 2024-02-16 at 9 49 04 AM" src="https://github.com/hpde/CNES/assets/22496475/1d03975a-7297-40f6-97db-35dcf84cf49b">

**Comment by tressahelvey** [comment]
Hello Daniele,
Was it your intention to name your SPASE records as indicated in the screen shot? It has been pointed out that they are not descriptive enough. I have added Lee and Shing to this notice as well. Please let us know if you'd like to discuss the issue. Thank you. Tressa

**Comment by myriam62** [comment]
Hi,
We use the ResourceName to build the tree in AMDA ( for example you can see 0.03 sec, 1 sec, 4s). A fuller description is given in other fields.
![arbre_amda](https://github.com/hpde/CNES/assets/81301504/318181a8-5d6c-41ab-83a3-e43d0aef79a6)
If this is a problem, we can think of another solution.

Best regards,
Myriam

**Comment by berniegsfc** [comment]
AMDA should use the `//TemporalDescription/Cadence` value instead of the `//ResouceName` for cadence values.

**Comment by myriam62** [comment]
The cadence is well defined in TemporalDescription/Cadence.
We need to display the name of the dataset in a tree and we use the ResourceName to do this.

**Comment by berniegsfc** [comment]
Having a `ResourceName` value like you have make your SPASE XML files un/less usable in other systems like HDP.  If your SPASE files are only to be used in `AMDA`, then the current values are fine.

**Comment by BaptisteCecconi** [comment]
I agree with the comment from @berniegsfc. The SPASE records are not only for CDPP/AMDA, they can be used by other tools to discover CDPP/AMDA resources. If the `ResourceName` is cryptic, then it is a bit useless. I understand that CDPP/AMDA has a direct mapping between `ResourceName` and the AMDA tree display. There is some value in this, of course, but not to the detriment of external usage. 

So I suggest to change a bit the mapping and include more information in the SPASE `ResourceName`.

**Comment by sffung** [comment]
ResourceName should be a "full name" sufficient for identifying a resource uniquely. It should be a brief, textual description (see definition in SPASE dictionary) that corresponds to the ResourceID. Cadence can be included as a part of the ResourceName, but by itself cadence is not a full name of a resource (see an example for an MMS product: [https://hpde.io/NASA/NumericalData/MMS/1/FIELDS/FGM/Burst/Level2/PT0.0078125S.html]

**Comment by myriam62** [comment]
I understand what you mean. We will complete the descriptions for the ResourceName as soon as possible.

**Comment by sffung** [comment]
Hi Myriam,

Great, thanks! While we’re at it, I think we’ve also found other issues relating to the CDPP SPASE repository that are inconsistent with the SPASE registry. Lee Bargatze has been tasked to document some of our findings. We’d like to have a meeting (on Teams or Webex when we have a clearer picture) to discuss how we may resolve them.

Shing

From: myriam62 ***@***.***>
Reply-To: hpde/CNES ***@***.***>
Date: Wednesday, March 6, 2024 at 3:42 AM
To: hpde/CNES ***@***.***>
Cc: "Shing Fung (GSFC-6750)" ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [hpde/CNES] ResourceName values are not descriptive enough (Issue #5)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



I understand what you mean. We will complete the descriptions for the ResourceName as soon as possible.

**Comment by tressahelvey** [comment]
Hello Myriam, We are checking on the status of the modifying the ResourceName. Do you have a target date for completion?
Thank you.

**Comment by tressahelvey** [comment]
Closing Ticket
